version: '2'

services:
    flaskapp_swap:
        build: .
        ports: 
            - "8999:8999"
        image: omr_swap
        container_name: omr_swap
        environment:
            - VIRTUAL_HOST=flaskapp_omr.swap.io